workflow:
  name: "Pipeline for branch: $CI_COMMIT_BRANCH"

default:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

stages: # List of stages for jobs, and their order of execution
  - dev
  - stage

variables:
  HARBOR_REGISTRY: "container.kudev.com"
  SERVICE_NAME: "app-product"

.base:
  variables:
    APP_ENV: ''
  environment:
    name: $APP_ENV
    url: https://api-product-${APP_ENV}.eshop.com/
  tags:
    - runner04
  before_script:
    - export HARBOR_IMAGE="${HARBOR_REGISTRY}/eshop/${SERVICE_NAME}"
  script:
    - echo "Running ${APP_ENV} job ..."
    - echo $HARBOR_IMAGE
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${HARBOR_IMAGE}:${APP_ENV}"
      --skip-tls-verify
      --cache

dev-job:
  extends: .base
  stage: dev
  variables:
    APP_ENV: 'dev'
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"

stage-job:
  extends: .base
  stage: stage
  variables:
    APP_ENV: 'stage'
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_REF_NAME != "main"
      when: never
    - when: manual