version: "3.8"

services:
  server:
    container_name: service_go
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - grpc-net
    restart: always

networks:
  grpc-net:
    driver: bridge
