# Choose whatever you want, version >= 1.16
FROM golang:1.21-alpine

# Update the package repository and install libvips
RUN apk update && apk add --no-cache alpine-sdk vips-dev

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]
